name: 'acme_fraud_lakehouse'
version: '1.0.0'
config-version: 2

profile: 'acme_fraud_profile'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  acme_fraud_lakehouse:
    +materialized: table
    +cluster_by: ["customer_id", "loyalty_tier"]
