acme_fraud_profile:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: acme-l400-part3-eri-01
      dataset: fraud_features_gold
      threads: 8
      timeout_seconds: 300
      location: us-central1
      priority: interactive
